parameters:
    fos_rest.view_handler.default.class: KwfBundle\Rest\ViewHandler

services:
    kwf.session.storage:
        class: KwfBundle\HttpFoundation\Session\KwfSessionStorage
        public: false

    kwf.rest.apidoc.extractor:
        class: KwfBundle\Rest\ApiDocExtractor
        tags:
            - { name: nelmio_api_doc.extractor.handler }
        public: false

    kwf_authenticator:
        class:  KwfBundle\Security\KwfUserAuthenticator
        arguments: [@kwf.user.model]
        public: false

    kwf.user.model:
        class: Kwf_User_Model
        factory: ['Kwf_Registry', get]
        arguments: ['userModel']

    kwf_user_provider:
        class: KwfBundle\Security\KwfUserProvider
        arguments: [@kwf.user.model]

    kwf.security.entrypoint.api:
        class: KwfBundle\Security\EntryPoint

    kwf.model_normalizer:
        class: KwfBundle\Serializer\KwfModelNormalizer
        tags:
            - { name: serializer.normalizer }
        public: false

    kwf.submit_handler_error_normalizer:
        class: KwfBundle\Serializer\SubmitHandlerErrorNormalizer
        arguments: ['@translator']
        tags:
            - { name: serializer.normalizer, priority: -10 }
        public: false
